class CurrencyInfo {
  final String code;
  final String name;
  final String symbol;
  final int minorUnits;

  const CurrencyInfo(this.code, this.name, this.symbol, this.minorUnits);
}

class CurrencyUtils {
  CurrencyUtils._();

  static const currencies = <CurrencyInfo>[
    CurrencyInfo('AED', 'UAE Dirham', 'د.إ', 2),
    CurrencyInfo('AFN', 'Afghan Afghani', '؋', 2),
    CurrencyInfo('ALL', 'Albanian Lek', 'L', 2),
    CurrencyInfo('AMD', 'Armenian Dram', '֏', 2),
    CurrencyInfo('ANG', 'Netherlands Antillian Guilder', 'ƒ', 2),
    CurrencyInfo('AOA', 'Angolan Kwanza', 'Kz', 2),
    CurrencyInfo('ARS', 'Argentine Peso', '\$', 2),
    CurrencyInfo('AUD', 'Australian Dollar', 'A\$', 2),
    CurrencyInfo('AWG', 'Aruban Florin', 'ƒ', 2),
    CurrencyInfo('AZN', 'Azerbaijani Manat', '₼', 2),
    CurrencyInfo('BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM', 2),
    CurrencyInfo('BBD', 'Barbadian Dollar', '\$', 2),
    CurrencyInfo('BDT', 'Bangladeshi Taka', '৳', 2),
    CurrencyInfo('BGN', 'Bulgarian Lev', 'лв', 2),
    CurrencyInfo('BHD', 'Bahraini Dinar', '.د.ب', 3),
    CurrencyInfo('BIF', 'Burundian Franc', 'FBu', 0),
    CurrencyInfo('BMD', 'Bermudian Dollar', '\$', 2),
    CurrencyInfo('BND', 'Brunei Dollar', '\$', 2),
    CurrencyInfo('BOB', 'Bolivian Boliviano', 'Bs.', 2),
    CurrencyInfo('BRL', 'Brazilian Real', 'R\$', 2),
    CurrencyInfo('BSD', 'Bahamian Dollar', '\$', 2),
    CurrencyInfo('BTN', 'Bhutanese Ngultrum', 'Nu.', 2),
    CurrencyInfo('BWP', 'Botswana Pula', 'P', 2),
    CurrencyInfo('BYN', 'Belarusian Ruble', 'Br', 2),
    CurrencyInfo('BZD', 'Belize Dollar', 'BZ\$', 2),
    CurrencyInfo('CAD', 'Canadian Dollar', 'CA\$', 2),
    CurrencyInfo('CDF', 'Congolese Franc', 'FC', 2),
    CurrencyInfo('CHF', 'Swiss Franc', 'Fr.', 2),
    CurrencyInfo('CLP', 'Chilean Peso', '\$', 0),
    CurrencyInfo('CNY', 'Chinese Yuan Renminbi', '¥', 2),
    CurrencyInfo('COP', 'Colombian Peso', '\$', 2),
    CurrencyInfo('CRC', 'Costa Rican Colon', '₡', 2),
    CurrencyInfo('CUP', 'Cuban Peso', '₱', 2),
    CurrencyInfo('CVE', 'Cape Verdean Escudo', 'Esc', 2),
    CurrencyInfo('CZK', 'Czech Koruna', 'Kč', 2),
    CurrencyInfo('DJF', 'Djiboutian Franc', 'Fdj', 0),
    CurrencyInfo('DKK', 'Danish Krone', 'kr', 2),
    CurrencyInfo('DOP', 'Dominican Peso', 'RD\$', 2),
    CurrencyInfo('DZD', 'Algerian Dinar', 'د.ج', 2),
    CurrencyInfo('EGP', 'Egyptian Pound', '£', 2),
    CurrencyInfo('ERN', 'Eritrean Nakfa', 'Nfk', 2),
    CurrencyInfo('ETB', 'Ethiopian Birr', 'Br', 2),
    CurrencyInfo('EUR', 'Euro', '€', 2),
    CurrencyInfo('FJD', 'Fiji Dollar', 'FJ\$', 2),
    CurrencyInfo('FKP', 'Falkland Islands Pound', '£', 2),
    CurrencyInfo('GBP', 'Pound Sterling', '£', 2),
    CurrencyInfo('GEL', 'Georgian Lari', '₾', 2),
    CurrencyInfo('GHS', 'Ghanaian Cedi', 'GH₵', 2),
    CurrencyInfo('GIP', 'Gibraltar Pound', '£', 2),
    CurrencyInfo('GMD', 'Gambian Dalasi', 'D', 2),
    CurrencyInfo('GNF', 'Guinean Franc', 'FG', 0),
    CurrencyInfo('GTQ', 'Guatemalan Quetzal', 'Q', 2),
    CurrencyInfo('GYD', 'Guyanese Dollar', '\$', 2),
    CurrencyInfo('HKD', 'Hong Kong Dollar', 'HK\$', 2),
    CurrencyInfo('HNL', 'Honduran Lempira', 'L', 2),
    CurrencyInfo('HRK', 'Croatian Kuna', 'kn', 2),
    CurrencyInfo('HTG', 'Haitian Gourde', 'G', 2),
    CurrencyInfo('HUF', 'Hungarian Forint', 'Ft', 2),
    CurrencyInfo('IDR', 'Indonesian Rupiah', 'Rp', 2),
    CurrencyInfo('ILS', 'Israeli New Shekel', '₪', 2),
    CurrencyInfo('INR', 'Indian Rupee', '₹', 2),
    CurrencyInfo('IQD', 'Iraqi Dinar', 'ع.د', 3),
    CurrencyInfo('IRR', 'Iranian Rial', '﷼', 2),
    CurrencyInfo('ISK', 'Icelandic Króna', 'kr', 0),
    CurrencyInfo('JMD', 'Jamaican Dollar', 'J\$', 2),
    CurrencyInfo('JOD', 'Jordanian Dinar', 'د.ا', 3),
    CurrencyInfo('JPY', 'Japanese Yen', '¥', 0),
    CurrencyInfo('KES', 'Kenyan Shilling', 'KSh', 2),
    CurrencyInfo('KGS', 'Kyrgyzstani Som', 'лв', 2),
    CurrencyInfo('KHR', 'Cambodian Riel', '៛', 2),
    CurrencyInfo('KMF', 'Comorian Franc', 'CF', 0),
    CurrencyInfo('KPW', 'North Korean Won', '₩', 2),
    CurrencyInfo('KRW', 'South Korean Won', '₩', 0),
    CurrencyInfo('KWD', 'Kuwaiti Dinar', 'د.ك', 3),
    CurrencyInfo('KYD', 'Cayman Islands Dollar', '\$', 2),
    CurrencyInfo('KZT', 'Kazakhstani Tenge', '₸', 2),
    CurrencyInfo('LAK', 'Lao Kip', '₭', 2),
    CurrencyInfo('LBP', 'Lebanese Pound', 'ل.ل', 2),
    CurrencyInfo('LKR', 'Sri Lanka Rupee', '₨', 2),
    CurrencyInfo('LRD', 'Liberian Dollar', '\$', 2),
    CurrencyInfo('LSL', 'Lesotho Loti', 'M', 2),
    CurrencyInfo('LYD', 'Libyan Dinar', 'ل.د', 3),
    CurrencyInfo('MAD', 'Moroccan Dirham', 'د.م.', 2),
    CurrencyInfo('MDL', 'Moldovan Leu', 'L', 2),
    CurrencyInfo('MGA', 'Malagasy Ariary', 'Ar', 2),
    CurrencyInfo('MKD', 'Macedonian Denar', 'ден', 2),
    CurrencyInfo('MMK', 'Myanmar Kyat', 'K', 2),
    CurrencyInfo('MNT', 'Mongolian Tögrög', '₮', 2),
    CurrencyInfo('MOP', 'Macanese Pataca', 'MOP\$', 2),
    CurrencyInfo('MRU', 'Mauritanian Ouguiya', 'UM', 2),
    CurrencyInfo('MUR', 'Mauritian Rupee', '₨', 2),
    CurrencyInfo('MVR', 'Maldivian Rufiyaa', 'Rf', 2),
    CurrencyInfo('MWK', 'Malawian Kwacha', 'MK', 2),
    CurrencyInfo('MXN', 'Mexican Peso', 'MX\$', 2),
    CurrencyInfo('MYR', 'Malaysian Ringgit', 'RM', 2),
    CurrencyInfo('MZN', 'Mozambican Metical', 'MT', 2),
    CurrencyInfo('NAD', 'Namibian Dollar', '\$', 2),
    CurrencyInfo('NGN', 'Nigerian Naira', '₦', 2),
    CurrencyInfo('NIO', 'Nicaraguan Córdoba', 'C\$', 2),
    CurrencyInfo('NOK', 'Norwegian Krone', 'kr', 2),
    CurrencyInfo('NPR', 'Nepalese Rupee', '₨', 2),
    CurrencyInfo('NZD', 'New Zealand Dollar', 'NZ\$', 2),
    CurrencyInfo('OMR', 'Omani Rial', 'ر.ع.', 3),
    CurrencyInfo('PAB', 'Panamanian Balboa', 'B/.', 2),
    CurrencyInfo('PEN', 'Peruvian Sol', 'S/.', 2),
    CurrencyInfo('PGK', 'Papua New Guinea Kina', 'K', 2),
    CurrencyInfo('PHP', 'Philippine Peso', '₱', 2),
    CurrencyInfo('PKR', 'Pakistani Rupee', '₨', 2),
    CurrencyInfo('PLN', 'Polish Zloty', 'zł', 2),
    CurrencyInfo('PYG', 'Paraguayan Guarani', '₲', 0),
    CurrencyInfo('QAR', 'Qatari Riyal', 'ر.ق', 2),
    CurrencyInfo('RON', 'Romanian Leu', 'lei', 2),
    CurrencyInfo('RSD', 'Serbian Dinar', 'дин', 2),
    CurrencyInfo('RUB', 'Russian Ruble', '₽', 2),
    CurrencyInfo('RWF', 'Rwandan Franc', 'FRw', 0),
    CurrencyInfo('SAR', 'Saudi Riyal', '﷼', 2),
    CurrencyInfo('SBD', 'Solomon Islands Dollar', 'SI\$', 2),
    CurrencyInfo('SCR', 'Seychellois Rupee', '₨', 2),
    CurrencyInfo('SDG', 'Sudanese Pound', 'ج.س.', 2),
    CurrencyInfo('SEK', 'Swedish Krona', 'kr', 2),
    CurrencyInfo('SGD', 'Singapore Dollar', 'S\$', 2),
    CurrencyInfo('SHP', 'Saint Helena Pound', '£', 2),
    CurrencyInfo('SLL', 'Sierra Leonean Leone', 'Le', 2),
    CurrencyInfo('SOS', 'Somali Shilling', 'Sh', 2),
    CurrencyInfo('SRD', 'Surinamese Dollar', '\$', 2),
    CurrencyInfo('SSP', 'South Sudanese Pound', '£', 2),
    CurrencyInfo('STN', 'São Tomé and Príncipe Dobra', 'Db', 2),
    CurrencyInfo('SVC', 'Salvadoran Colón', '\$', 2),
    CurrencyInfo('SYP', 'Syrian Pound', '£', 2),
    CurrencyInfo('SZL', 'Eswatini Lilangeni', 'E', 2),
    CurrencyInfo('THB', 'Thai Baht', '฿', 2),
    CurrencyInfo('TJS', 'Tajikistani Somoni', 'SM', 2),
    CurrencyInfo('TMT', 'Turkmenistani Manat', 'T', 2),
    CurrencyInfo('TND', 'Tunisian Dinar', 'د.ت', 3),
    CurrencyInfo('TOP', 'Tongan Paʻanga', 'T\$', 2),
    CurrencyInfo('TRY', 'Turkish Lira', '₺', 2),
    CurrencyInfo('TTD', 'Trinidad and Tobago Dollar', 'TT\$', 2),
    CurrencyInfo('TWD', 'New Taiwan Dollar', 'NT\$', 2),
    CurrencyInfo('TZS', 'Tanzanian Shilling', 'TSh', 2),
    CurrencyInfo('UAH', 'Ukrainian Hryvnia', '₴', 2),
    CurrencyInfo('UGX', 'Ugandan Shilling', 'USh', 0),
    CurrencyInfo('USD', 'US Dollar', '\$', 2),
    CurrencyInfo('UYU', 'Uruguayan Peso', '\$U', 2),
    CurrencyInfo('UZS', 'Uzbekistani Som', 'лв', 2),
    CurrencyInfo('VES', 'Venezuelan Bolívar', 'Bs.', 2),
    CurrencyInfo('VND', 'Vietnamese Đồng', '₫', 0),
    CurrencyInfo('VUV', 'Vanuatu Vatu', 'VT', 0),
    CurrencyInfo('WST', 'Samoan Tālā', 'WS\$', 2),
    CurrencyInfo('XAF', 'Central African CFA Franc', 'FCFA', 0),
    CurrencyInfo('XCD', 'East Caribbean Dollar', 'EC\$', 2),
    CurrencyInfo('XOF', 'West African CFA Franc', 'CFA', 0),
    CurrencyInfo('XPF', 'CFP Franc', '₣', 0),
    CurrencyInfo('YER', 'Yemeni Rial', '﷼', 2),
    CurrencyInfo('ZAR', 'South African Rand', 'R', 2),
    CurrencyInfo('ZMW', 'Zambian Kwacha', 'ZK', 2),
  ];

  static List<String> get codes => currencies.map((c) => c.code).toList();

  static final Map<String, CurrencyInfo> _byCode = {
    for (final currency in currencies) currency.code: currency,
  };

  static String symbolFor(String code) => _byCode[code]?.symbol ?? code;
}
